### ISSUE TITLE
filtering / ordering products

### ISSUE THREAD

**Issue by acfi-network** [Yasser-G/Sylius-Shop-API-Client#1]
Hi Yasser,
Thanks for this very great work.
Will you add product filtering ?
Best regards
MAthieu

**Comment by Yasser-G** [comment]
Hello MAthieu.

Thanks for your encourages comment, but I didn't find this request in this [file](https://github.com/Sylius/ShopApiPlugin/blob/master/doc/swagger.yml) yet.

Once this file is updated, I have to add any update to my api client, or you can submit a PR following the schema, or simply open new issue starting with feature request keyword.

If you need to use it now you can use [CustomEndpoint extending](https://github.com/Yasser-G/Sylius-Shop-API-Client#custom-endpoint-extending).


Thanks.

**Comment by acfi-network** [comment]
Hello Yasser,

My bad, you are right, I thought you used sylius official API.

Thanks for your answer, and once again, good job !

Mathieu

De : Yasser-G <notifications@github.com>
Répondre à : Yasser-G/Sylius-Shop-API-Client <reply@reply.github.com>
Date : mardi 18 février 2020 à 09:35
À : Yasser-G/Sylius-Shop-API-Client <Sylius-Shop-API-Client@noreply.github.com>
Cc : Mathieu dureisseix <mdureisseix@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [Yasser-G/Sylius-Shop-API-Client] filtering / ordering products (#1)


Hello MAthieu.

Thanks for your encourages comment, but I didn't find this request in this file<https://github.com/Sylius/ShopApiPlugin/blob/master/doc/swagger.yml> yet.

Once this file is updated, I have to add any update to my api client, or you can submit a PR following the schema, or simply open new issue starting with feature request keyword.

If you need to use it now you can use CustomEndpoint extending<https://github.com/Yasser-G/Sylius-Shop-API-Client#custom-endpoint-extending>.

Thanks.

**Comment by Yasser-G** [comment]
Hello Mathieu, The file I mentioned in my reply refers to official sylius shop API, If they support filtering / ordering products please let me know.

Thanks.

**Comment by acfi-network** [comment]
Hello Yasser,

Yes this is an official plugin, but the api of sylius admin can also be used for filtering https://docs.sylius.com/en/latest/api/sorting_and_filtration.html.

Best regards
MAthieu

De : Yasser-G <notifications@github.com>
Répondre à : Yasser-G/Sylius-Shop-API-Client <reply@reply.github.com>
Date : jeudi 20 février 2020 à 21:13
À : Yasser-G/Sylius-Shop-API-Client <Sylius-Shop-API-Client@noreply.github.com>
Cc : Mathieu dureisseix <mdureisseix@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [Yasser-G/Sylius-Shop-API-Client] filtering / ordering products (#1)


Hello Mathieu, The file I mentioned in my reply refers to official sylius shop API, If they support filtering / ordering products please let me know.

Thanks.
